sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 314159
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    bucket-name: sky-take-out
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wxe7abe54321dddb92
    secret: c5b0cab0323d572e2a6ed7d0c4b3b1fb